### PR TITLE
Multiple Hostname Entries

### PR DESCRIPTION
**Pull request by TheDropZone**
While using this awesome library, I found out that we were losing data under the <Hostnames><Hostname> tags. The current version only stores the last Hostname entry under the Hostnames tag. If Nmap returns multiple Hostname entries for a given host, we lose all but the last Hostname. I'm proposing a similar construct to the Host.addresses where we store all Hostname objects in an ArrayList so we don't lose that data.

Thanks!

### CODE REVIEW

**Comment by TheDropZone** [comment]
@narkisr Got the import added in and it is compiling! Woohoo. I did try running the tests but as I am on a Windows with a different Nmap location, not all of them passed.

**Comment by TheDropZone** [comment]
@narkisr Anything else on this branch I need to clean up? Thanks!

**Comment by narkisr** [comment]
Hi @TheDropZone the main thing left to do is to make sure the build stay green and that all the tests are passing (https://travis-ci.org/narkisr/nmap4j). 

Its recommended to run them under an Ubuntu machine (could be a VM), the current setup requires symlinking the nmap binary to /usr/local/nmap

Ill try to take a look on which tests break and if a quick fix is possible.

Thanks

**Comment by narkisr** [comment]
Ok doing a quick run of the tests I can see that only one is failing:

https://github.com/narkisr/nmap4j/blob/master/src/test/java/org/nmap4j/parsers/NMapXmlHandlerTest.java#L25 

As far as I can tell its because the hostnames value is null and get passed in as the event payload in:

https://github.com/narkisr/nmap4j/blob/master/src/test/java/org/nmap4j/parsers/NMapXmlHandlerTest.java#L67

I still need to think what the proper fix is in this case.

**Comment by narkisr** [comment]
Hi @TheDropZone iv done another analysis of the code (the model is a bit confusing) and it seems using a similar approach to Ports tag makes this change easier to implement while keeping all the tests green.

Please have a look at https://github.com/narkisr/nmap4j/pull/12 and see if it works for your use case.

Thanks

**Pull request closed without merging**
